In [8]:
def distSquared(point1, point2):
    assert point1.shape == point2.shape
    return np.sum(np.square(point2-point1))

In [73]:
def findClosestCentroids(X, centroids):
    ci = np.zeros((X.shape[0],1))
    #Loop through each data point in X
    for m in range(0,ci.shape[0]):
        point = X[m]
        #Compare this point to each centroid,
        #Keep track of shortest distance and index of shortest distance
        mindist, idx = 9999999, 0
        for i in range(0,centroids.shape[0]):
            centroid = centroids[i]
            distsquared = distSquared(centroid,point)
            if distsquared < mindist:
                mindist = distsquared
                idx = i
        #With the best index found, modify the result ci vector
        ci[m] = idx    
    return ci

In [97]:
def findClosestCentroid(X,centroids):
    K = len(centroids)
    ci = np.zeros((len(X), 1))
    for m in range(0,len(X)):
        distances = np.zeros((len(centroids), 1))
        for k in range(0,K):
            distances[k] = sum((X[m]-centroids[k]) ** 2 )
        x= min(distances)
        index = np.argmin(distances)
        ci[m] = index
    return ci


In [96]:
def computeCentroids(X, ci):
    subX=[] 
    for i in range(0,len(np.unique(ci))):
        subX.append(np.array([X[m] for m in range(0,X.shape[0]) if ci[m] == i]))#creates subset of X with common cluster index
    return np.array([np.mean(thisX,axis=0) for thisX in subX]) #finds mean of each set of points in clusters

In [77]:
def kmeans(file,cluster_size):
    data = pd.read_csv(file, sep=" ", header=None)
    row,col=data.shape
    X=data.iloc[:,:].values
    centroids=initCentroids(X,cluster_size)
    #pdb.set_trace()
    for i in range(0,100):
        ci=findClosestCentroid(X,centroids)
        #print(ci)
        centroids=computeCentroids(X,ci)
    #pdb.set_trace()
    print(centroids)
    df=pd.DataFrame(data=centroids)
    df.to_csv('clusters.txt', sep=' ',index=False,header = False)

In [40]:
def initCentroids(X, K):
    rand_indices = sample(range(0,X.shape[0]),K)
    return np.array([X[i] for i in rand_indices])

In [66]:
def runKMeans(X, K):
    """
    Function that actually does the iterations
    """
    centroid_history = []
    current_centroids = initCentroids(X, K)
    for myiter in range(0,10000):
        centroid_history.append(current_centroids)
        idxs = findClosestCentroids(X,current_centroids)
        current_centroids = computeCentroids(X,idxs)
        
    return idxs, centroid_history,current_centroids

In [71]:
ci,ch,c=runKMeans(X, 2)

In [72]:
c

array([[0.36666667, 0.7       , 0.53333333],
       [5.2       , 6.5       , 7.55      ]])

In [65]:
X

array([[0.1, 0.4, 0.2],
       [0.6, 0.1, 0.5],
       [0.4, 1.6, 0.9],
       [1.2, 3.4, 6.5],
       [9.2, 9.6, 8.6]])

In [101]:
kmeans('Points.txt',2)


[[0.36666667 0.7        0.53333333]
 [5.2        6.5        7.55      ]]


In [7]:
print(xrange(1))

NameError: name 'xrange' is not defined

In [6]:
import sys,pandas as pd,numpy as np,random,pdb
from random import sample

def findClosestCentroids(X, centroids):
    ci = np.zeros((X.shape[0],1))
    #Loop through each data point in X
    for m in range(0,ci.shape[0]):
        point = X[m]
        #Compare this point to each centroid,
        #Keep track of shortest distance and index of shortest distance
        mindist, idx = 9999999, 0
        for i in range(0,centroids.shape[0]):
            centroid = centroids[i]
            distsquared = distSquared(centroid,point)
            if distsquared < mindist:
                mindist = distsquared
                idx = i
        #With the best index found, modify the result ci vector
        ci[m] = idx    
    return ci

def computeMeans(X,ci,K):
    row,col=X.shape
    centroids = np.zeros((K, col))
    for i in range(0,K):
        c=len(np.where(ci==i)[0])
        if(c!=0):
            centroids[i] = (1 / c) * sum(sum(X[np.where(ci==i)[0]]))
    return centroids
        
def initCentroids(X, K):
    rand_indices = sample(range(0,X.shape[0]),K)
    return np.array([X[i] for i in rand_indices])

def kmeans(file,cluster_size):
    data = pd.read_csv(file, sep=" ", header=None)
    row,col=data.shape
    X=data.iloc[:,:].values
    centroids=initCentroids(X,cluster_size)
    #pdb.set_trace()
    for i in range(0,100):
        ci=findClosestCentroid(X,centroids)
        #print(ci)
        centroids=computeMeans(X,ci,cluster_size)
    #pdb.set_trace()
    print(centroids)
    df=pd.DataFrame(data=centroids)
    df.to_csv('clusters.txt', sep=' ',index=False,header = False)


if __name__ == "__main__":
    kmeans('Points.txt',2)

[[8.66 8.66 8.66]
 [0.   0.   0.  ]]


In [106]:
import sys,pandas as pd,numpy as np
from random import sample

def findClosestCentroid(X,centroids):
    K = len(centroids)
    ci = np.zeros((len(X), 1))
    for m in range(0,len(X)):
        distances = np.zeros((len(centroids), 1))
        for k in range(0,K):
            distances[k] = sum((X[m] - centroids[k]) ** 2 )
        x= min(distances)
        index = np.argmin(distances)
        ci[m] = index
    return ci

def computeCentroids(X, ci):
    subX=[] 
    for i in range(0,len(np.unique(ci))):
        subX.append(np.array([X[m] for m in range(0,X.shape[0]) if ci[m] == i]))#creates subset of X with common cluster index
    return np.array([np.mean(thisX,axis=0) for thisX in subX]) #finds mean of each set of points in clusters
        
def initCentroids(X, K):
    rand_indices = sample(range(0,X.shape[0]),K) # selects random indices from X
    return np.array([X[i] for i in rand_indices]) # return ndarray with values of the random indices

def kmeans(file,cluster_size):
    data = pd.read_csv(file, sep=" ", header=None)
    row,col=data.shape
    X=data.iloc[:,:].values
    centroids=initCentroids(X,cluster_size)
    for i in range(0,100):
        ci=findClosestCentroid(X,centroids)
        centroids=computeCentroids(X,ci)
    df=pd.DataFrame(data=centroids)
    df.to_csv('clusters.txt', sep=' ',index=False,header = False)

if __name__ == "__main__":
    kmeans('points.txt',2)

In [27]:
import pandas as pd
c='points.txt'
data = pd.read_csv(c, sep=" ", header=None)
data

0    1    2
0  0.1  0.4  0.2
1  0.6  0.1  0.5
2  0.4  1.6  0.9
3  1.2  3.4  6.5
4  9.2  9.6  8.6

In [29]:
X=data.iloc[:,:].values


In [12]:
data = pd.read_csv(c, sep=" ", header=None)
X=data.iloc[:,:].values

In [14]:
from sklearn.cluster import KMeans
kmeans = KMeans(algorithm='full',init='random',n_clusters=2, random_state=0).fit(X)

In [15]:
kmeans

KMeans(algorithm='full', copy_x=True, init='random', max_iter=300,
    n_clusters=2, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=0, tol=0.0001, verbose=0)

In [16]:
kmeans.cluster_centers_

array([[9.2  , 9.6  , 8.6  ],
       [0.575, 1.375, 2.025]])

In [20]:
file = open('testfile.txt','w') 
 
file.write(str(kmeans.cluster_centers_[0]) )

file.close() 

In [189]:
file = open('testfile.txt','r') 
 
x=file.read()

file.close() 
X

array([[0.1, 0.4, 0.2],
       [0.6, 0.1, 0.5],
       [0.4, 1.6, 0.9],
       [1.2, 3.4, 6.5],
       [9.2, 9.6, 8.6]])

In [188]:
sum((X[1]-[0.2, 0.0, 0.2])**2)

array([0.16, 0.01, 0.09])

In [23]:
from random import sample
centroids = np.zeros((2, X.shape[1]))
rand_indices = sample(range(0,X.shape[0]),2)
centroids = np.array([X[i] for i in rand_indices])
centroids  


array([[0.4, 1.6, 0.9],
       [0.1, 0.4, 0.2]])

In [8]:
[9.2, 3.3, 8.4] in centroids

True

In [10]:
np.delete(centroids,[9.2, 3.3, 8.4],axis=0)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: using a non-integer array as obj in delete will result in an error in the future
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: in the future out of bounds indices will raise an error instead of being ignored by `numpy.delete`.
  """Entry point for launching an IPython kernel.


array([[9.2, 9.6, 8.6],
       [9.2, 9.6, 8.6]])

In [90]:
def kMeansInitCentroids(X, K):
    centroids = np.zeros((K, X.shape[1]))
    for i in range(0,K):
        if(not(random.choice(X) in centroids)):    
            centroids[i]=random.choice(X)


In [ ]:
centroids=initCentroids(X,K)
for i in range(0,50):
    ci=findClosestCentroid(X,centroids)
    centroids=computeMeans(X,ci,K)
    


In [ ]:
def findClosestCentroid(X,centroids):
    K = len(centroids)
    ci = np.zeros((len(X), 1))
    for m in range(0,len(X)):
        distances = np.zeros((len(centroids), 1));
    for k in range(0,K);
        distances[k] = sum(sum((X - centroids) ** 2 ));

    x= min(distances)
    index = np.argmin(distances)
    ci[m] = index

In [ ]:
def computeMeans(X,ci,K):
    row,col=X.shape
    centroids = np.zeros((K, col))
    for i in range(0,K):
        centroids[i] = (1 / len(np.where(ci==i)[0])) * sum(sum(X[np.where(ci==i)[0]]))


In [48]:
sum(sum((distances-np.ones((10, 1)))**2))

73.0

In [76]:
np.where(distances==9)[0]
sum(sum(distances[np.where(distances==9)[0]]))


9.0

In [40]:
import numpy as np
help(np.zeros)
np.zeros((5, 1))

Help on built-in function zeros in module numpy.core.multiarray:

zeros(...)
    zeros(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, filled with zeros.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    
    Returns
    -------
    out : ndarray
        Array of zeros with the given shape, dtype, and order.
    
    See Also
    --------
    zeros_like : Return an array of zeros with shape and type of input.
    ones_like : Return an array of ones with shape and type of input.
    empty_like : Return an empty array with shape and type of input.
    ones : Return a new array setting v

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

ValueError: not enough values to unpack (expected 2, got 1)

In [35]:
np.argmax(distances)

1

NameError: name 'find' is not defined